//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_ICS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fms_db_icsEntities : DbContext
    {
        public fms_db_icsEntities()
            : base("name=fms_db_icsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAction> AdminActions { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<DocumentVerification> DocumentVerifications { get; set; }
        public virtual DbSet<EligibilityCriteria> EligibilityCriterias { get; set; }
        public virtual DbSet<ForgotPasswordRequest> ForgotPasswordRequests { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserCard> UserCards { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
