//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS_ICS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PurchaseID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> TenureMonths { get; set; }
        public Nullable<decimal> MonthlyEMI { get; set; }
        public Nullable<decimal> RemainingEMI { get; set; }
        public Nullable<System.DateTime> LastPaidDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
